### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bmerigan** [alepop/stencil-env#111]
I see the below error message when StencilJs tries to build/compile.
```
Rollup: Plugin Error
Cannot convert undefined or null to object (plugin: env, transform)
```

As far as I can tell I've used it the same way as the example, with a .env file at project root.  My IDE is seeing the .env file and correctly hinting the contents.
.env
```javascript
apiUrl=https://mysite.com/api
```

stencil.config.ts
```javascript
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { env } from '@alepop/stencil-env';
export const config: Config = {
  plugins: [
    sass(),
    env()
  ],
etc.
```

myappservice.ts
```javascript
private apiUrl = process.env.apiUrl + '/v1/myendpoint/';
```

package.json
```json
"devDependencies": {
    "@alepop/stencil-env": "^0.4.1",
    "@stencil/core": "1.8.11",
    "@stencil/sass": "1.0.1",
    "@types/jest": "24.0.23",
    "@types/puppeteer": "1.19.0",
    "del": "latest",
    "gulp": "^4.0.2",
    "gulp-run-command": "0.0.10",
    "jest": "24.9.0",
    "jest-cli": "24.9.0",
    "puppeteer": "1.19.0",
    "run-sequence": "latest"
  },
  "engines": {
    "node": ">=0.12.0"
  },
```

**Comment by bmerigan** [comment]
P.S. If I comment it out (3 lines) then the rest of the app works ok.

**Comment by alepop** [comment]
Hello @bmerigan! Sorry, but I can't reproduce your exception. I've tried to make a project from scratch with all your dependencies in a package list and everything works fine for me.

**Comment by bmerigan** [comment]
I was afraid you'd say that.  Thanks for looking into it.  I'll start the project from scratch and see what happens.  I tried a few 'env' plugins so there might be some carry-over / conflict.

**Comment by newtonmunene99** [comment]
I am also facing this issue, however, it doesn't seem to be happening on my local development environment, only when I deploy to Netlify.

Version
```
"@stencil/core": "^2.3.0",
```

My config
```
plugins: [
    sass(),
    // env(),
  ],
  rollupPlugins: {
    before: [env()],
    after: [
      // env(),
      nodePolyfills(),
    ],
  },
```
Stencil changed config options and added `rollupPlugins` field. I have tried using it in normal `plugins` field as well as `rollupPlugins.before` and `rollupPlugins.after`
