### ISSUE TITLE
Document that it's a literal string replacement, process.env object will not exist

### ISSUE THREAD

**Issue by beck24** [alepop/stencil-env#124]
I just spent forever trying to figure out why this wasn't working when I was trying to build a config service.

So I had code that looked for `process.env[key]` and I was getting `process.env is undefined` errors.

It's only when I looked to see what this plugin was doing under the hood that I understood what was happening.  I see there is at least one closed ticket about process.env being non-existent, I wonder if it was a similar situation.

Perhaps you can add something about this in the documentation explaining that process.env will not actually exist as a usable object.

Thanks!

**Comment by alepop** [comment]
@beck24 thank you
