### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by YYJay** [alepop/stencil-env#3]
Hi there, when i use stencil-env, i got `process is not defined`.here is my config
```js
import { Config } from '@stencil/core';
import { env } from '@alepop/stencil-env';

export const config: Config = {
  namespace: 'web-components-name',
  plugins: [
    env()
  ],
  outputTargets:[
    { type: 'dist' },
    { type: 'docs' },
    {
      type: 'www',
      serviceWorker: null // disable service workers
    }
  ],
};

```

**Comment by alepop** [comment]
Hey @YYJay thanks. What version of stencil/core do you use with this plugin?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YYJay** [comment]
> Hey @YYJay thanks. What version of stencil/core do you use with this plugin?
> 
> Sent with [GitHawk](http://githawk.com)

` "@stencil/core": "^0.16.4",`, I just want to use env in my stencil project.
Is it because stencil's runs in the browser? thanks

**Comment by alepop** [comment]
> > Hey @YYJay thanks. What version of stencil/core do you use with this plugin?
> > Sent with [GitHawk](http://githawk.com)
> 
> ` "@stencil/core": "^0.16.4",`, I just want to use env in my stencil project.
> Is it because stencil's runs in the browser? thanks

It should work even in a browser. It works for me as well. Do you use `.env` file in your project?

**Comment by YYJay** [comment]
> > > Hey @YYJay thanks. What version of stencil/core do you use with this plugin?
> > > Sent with [GitHawk](http://githawk.com)
> > 
> > 
> > ` "@stencil/core": "^0.16.4",`, I just want to use env in my stencil project.
> > Is it because stencil's runs in the browser? thanks
> 
> It should work even in a browser. It works for me as well. Do you use `.env` file in your project?


Can you provide an example in this project ? thank you very much

**Comment by YYJay** [comment]
> > > Hey @YYJay thanks. What version of stencil/core do you use with this plugin?
> > > Sent with [GitHawk](http://githawk.com)
> > 
> > 
> > ` "@stencil/core": "^0.16.4",`, I just want to use env in my stencil project.
> > Is it because stencil's runs in the browser? thanks
> 
> It should work even in a browser. It works for me as well. Do you use `.env` file in your project?

I do have `.env` file in my project
